.gitignore, scripts/fetch/hurricaneTrack.R, viz.yaml
i thiiiiink this will only download anew when there's a change to the remote timestamp for al152017_best_track.zip at http://www.nhc.noaa.gov/gis/best_track/. fingers crossed, and i'll keep watching it to make sure it updates within the next 6 hours
=> fetch hurricaneTrack with remote timestamp checking

scripts/fetch/fetch.precip_shapefiles.R, viz.yaml
This just pulls down raw data. I'll untar and process these files in a later step.
The logic I implemented is that as long as you don't  clean the cache, this will just pull down tar files you don't have yet in the full-day range we've specified. Should workout OK without refetch.
=> Precip fetcher

scripts/fetch/fetch.timesteps.R, scripts/process/process.storm_location.R, scripts/process/process.storm_track.R, scripts/read/read.json.R, scripts/read/read.shp.R, scripts/read/read.svg.R, scripts/visualize/plotting_utils.R, viz.yaml
these appear to work (copied from irma; they do build, i just don't know how correct everything is). i will add more comments & read more carefully after this pr; getting this up now so others have something to work with
=> process.storm_track and process.storm_location

.gitignore, README.md, scripts/fetch/fetch.timesteps.R, scripts/fetch/hurricaneTrack.R, scripts/process/process.storm_location.R
this is a follow-on to #16, just tidying up and making sure i understand what's happening
=> feeling good about hurricane-track, storm_track, and storm_location

preferences.yaml, scripts/fetch/fetch.nws_conversion.R, scripts/fetch/fetch.nws_data.R, scripts/fetch/fetch.sites.R, viz.yaml
Mostly just following Irma patterns
=> USGS and NWS site data

scripts/fetch/fetch.gage_data.R, scripts/process/process.storm_gage_height.R
Returns something that looks like:
```
Browse[2]> str(timestep.q)
List of 9
$ 50024950:List of 2
..$ x: POSIXct[1:63], format: "2017-09-17 20:00:00" "2017-09-17 21:00:00" "2017-09-17 22:00:00" "2017-09-17 23:00:00" ...
.. ..- attr(*, "names")="times1" "times2" "times3" "times4" ...
..$ y: num [1:63] NA NA NA NA 5.45 5.35 5.27 5.2 5.15 5.1 ...
$ 50027600:List of 2
..$ x: POSIXct[1:63], format: "2017-09-17 20:00:00" "2017-09-17 21:00:00" "2017-09-17 22:00:00" "2017-09-17 23:00:00" ...
.. ..- attr(*, "names")="times1" "times2" "times3" "times4" ...
..$ y: num [1:63] NA NA NA NA 8.11 8.12 8.11 8.11 8.11 8.12 ...
```
=> interpolating to json time steps.

scripts/fetch/fetch.gage_data.R
=> fetch error fix

scripts/fetch/fetch.gage_data.R, scripts/fetch/fetch.islands.R, scripts/fetch/fetch.nws_conversion.R, scripts/fetch/fetch.nws_data.R, scripts/fetch/fetch.sites.R, scripts/fetch/fetch.timesteps.R, scripts/fetch/fetch.view_limits.R, scripts/fetch/fetch.watermark.R, scripts/fetch/hurricaneTrack.R, viz.yaml
just leaving fetch.precip_shapefiles.R alone this time. might be able to address it more in a future PR, but wanted to get the easy stuff fixed
=> redo #27 except fetch.precip_shapefiles.R

scripts/process/process.classified_sites.R, scripts/process/process.sp_sites.R
```
[1] "Rio Grande de Arecibo below Utuado, PR"             
[2] "Rio Grande de Arecibo near San Pedro, PR"           
[3] "Rio Grande de Manati near Morovis, PR"              
[4] "Rio Grande de Manati at Ciales, PR"                 
[5] "Rio Grande de Manati at Hwy 2 near Manati, PR"      
[6] "Rio Cibuco below Corozal, PR"                       
[7] "Rio Cibuco at Vega Baja, PR"                        
[8] "Rio de La Plata at Proyecto La Plata, PR"           
[9] "Rio de La Plata at Comerio, PR"                     
[10] "Rio de La Plata below La Plata Damsite, PR"         
[11] "Rio de La Plata at Hwy 2 near Toa Alta, PR"         
[12] "Rio Piedras at Hato Rey, PR"                        
[13] "Rio Grande de Loiza at Hwy 183 San Lorenzo, PR"     
[14] "Rio Grande de Loiza at Caguas, …
```
=> Station Name tool tips.

layout/css/hurricane-svg.css, scripts/fetch/fetch.islands.R, scripts/process/process.precip_colors.R, scripts/visualize/visualize.hurricane_map.R, viz.yaml
=> sparks on the map

data/caption-text.yaml, scripts/process/process.classified_sites.R, viz.yaml
It'll need some styling, but it's a start.
=> Text in markdown

scripts/process/process.order_sites.R, scripts/process/process.sparks.R, viz.yaml
And a bit of cleanup. Right now the top sparkline is the eastern-most site, but could be changed pretty easily in `process.order_sites`
=> Dedicated sparkline site ordering process

data/caption-text.yaml
Just getting some draft text in here.
=> updated text

scripts/fetch/fetch.gage_data.R, scripts/process/process.classified_sites.R, scripts/process/process.order_sites.R, scripts/process/process.sparks.R, scripts/process/process.storm_gage_height.R
Heading out for a few hours, if someone wanted to review this, it's mostly working, but I currently managed to lose the hover text on the sparklines.
=> Cleanup of sparklines and spark hovers

layout/css/hurricane-svg.css, layout/js/animate.js, scripts/process/process.cell_precip.R, scripts/process/process.discharge_sparks.R, scripts/visualize/visualize.hurricane_map.R, viz.yaml
This doesn't look that different if your browser wasn't dogging before, but it made a huge difference for me. It solved my issue on #46 too. for #30 too but mainly a browser performance PR
=> pre-clipping precip cell data

layout/js/animate.js, scripts/process/process.classified_precip.R, viz.yaml
Also caching selectors within animation for optimization.
=> Fixed some animation issues

scripts/process/process.classified_sites.R, scripts/process/process.order_sites.R, scripts/process/process.sp_sites.R, scripts/process/process.sparks.R, viz.yaml
More linear dependency chain with sites now. Everything uses sp_sites. I changed the east west ordering to use projected coords, still east to west. toolstips on sparks are back. fixes #42
=> siteCapper in one place and got toolstips back

scripts/process/process.sparks.R, scripts/visualize/visualize.hurricane_map.R, viz.yaml
Ready to get hooked up in visualize.hurricane_map. I looked at finishing this for a bit and decided 😴 is needed before I try to figure that out. Hopefully @jread-usgs can finish it off.
=> Got blockers created the way they should be... I think.

layout/css/hurricane-svg.css, scripts/process/process.sparks.R, scripts/visualize/visualize.hurricane_map.R, viz.yaml
=> Layout style

layout/css/map-figure.css
=> spinning issue

layout/css/hurricane-svg.css, scripts/process/process.sparks.R
opacity and move down a smidge
=> blocker updates

scripts/process/process.storm_gage_height.R
=> Hard-code fix to problem gages

scripts/process/process.sparks.R
=> animation fix

scripts/process/process.classified_precip.R, viz.yaml
=> Precip Scale Update... much better!

scripts/process/process.sparks.R, scripts/visualize/visualize.hurricane_map.R, viz.yaml
This is almost there but I'm not seeing what's wrong. The gage blockers don't show up any more. I need to run and maybe someone else can finish this off or I will when I get back.
=> Mouse events applied to gage blockers, and now it works!

layout/js/animate.js, scripts/process/process.classified_sites.R
=> Adds flood class

layout/js/animate.js
* also clear cache when new svg is added
somewhat dependent on https://github.com/USGS-VIZLAB/vizlab/pull/231
=> change id selectors to handle duplicate ids :(

layout/css/hurricane-svg.css, scripts/visualize/visualize.hurricane_map.R, viz.yaml
=> style, more color bins, updated legend

scripts/process/process.cell_precip.R, viz.yaml
=> Virgin Islands!

scripts/visualize/visualize.hurricane_map.R
=> tiny text bump 
